# Generated by Django 5.0.2 on 2024-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_telegramuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
