# Generated by Django 5.0.2 on 2024-02-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('ramadan_image', models.ImageField(upload_to='media/ramadan_calendar')),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
