# Generated by Django 5.0.2 on 2024-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_ramadancalendar_remove_telegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(max_length=100)),
                ('prayer_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ramadancalendar',
            options={'ordering': ['id']},
        ),
    ]
